- name: Add OpenJDK PPA (optional for Ubuntu)
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install OpenJDK 21
  apt:
    name: "{{ jenkins_java_package }}"
    state: present

- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository (signed-by)
  copy:
    dest: /etc/apt/sources.list.d/jenkins.list
    content: |
      deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes
